<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: study.proto

namespace App\Grpc\StudyProto\Study;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>study.StudyResponse</code>
 */
class StudyResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string session_id = 1;</code>
     */
    protected $session_id = '';
    /**
     * Generated from protobuf field <code>string subject = 2;</code>
     */
    protected $subject = '';
    /**
     * Generated from protobuf field <code>string scheduled_at = 3;</code>
     */
    protected $scheduled_at = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $session_id
     *     @type string $subject
     *     @type string $scheduled_at
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\StudyProto\GPBMetadata\Study::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string session_id = 1;</code>
     * @return string
     */
    public function getSessionId()
    {
        return $this->session_id;
    }

    /**
     * Generated from protobuf field <code>string session_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->session_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subject = 2;</code>
     * @return string
     */
    public function getSubject()
    {
        return $this->subject;
    }

    /**
     * Generated from protobuf field <code>string subject = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSubject($var)
    {
        GPBUtil::checkString($var, True);
        $this->subject = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string scheduled_at = 3;</code>
     * @return string
     */
    public function getScheduledAt()
    {
        return $this->scheduled_at;
    }

    /**
     * Generated from protobuf field <code>string scheduled_at = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setScheduledAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->scheduled_at = $var;

        return $this;
    }

}

