<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: study.proto

namespace App\Grpc\StudyProto\GPBMetadata;

class Study
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xD7\x01\x0A\x0Bstudy.proto\x12\x05study\"\x1F\x0A\x0CStudyRequest\x12\x0F\x0A\x07user_id\x18\x01 \x01(\x09\"J\x0A\x0DStudyResponse\x12\x12\x0A\x0Asession_id\x18\x01 \x01(\x09\x12\x0F\x0A\x07subject\x18\x02 \x01(\x09\x12\x14\x0A\x0Cscheduled_at\x18\x03 \x01(\x092L\x0A\x0CStudyService\x12<\x0A\x0FGetStudySession\x12\x13.study.StudyRequest\x1A\x14.study.StudyResponseb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

